### ISSUE TITLE
S3 Access via HTTP proxy

### ISSUE THREAD

**Issue by chris-rock** [wal-e/wal-e#129]
unfortunately the features available via boto cannot be used with wal-e. Do you have a preferred way for requesting aws via a proxy?

**Comment by FlorianHeigl** [comment]
If one of the project people has a second, reading the thread of #131 it says proxy support doesn't need go in, but #129 here was closed pointing at this while no code was created to work w/proxy. 
if I grep -R the whole source for "proxy" I surely find no mention of S3_PROXY_HOST or such. Actually, nothing at all.


basically, trying to get proxy working in boto or in wal-e is just killing me. 

If I understand correctly, wal-e zaps the proxy settings made in boto.cfg even if they're corretly set up, but doesn't bring any of it's own?

I might have just failed in my tries, but it seems more like this issue was closed by mistake.
