### ISSUE TITLE
Travis CI / tox tests are broken

### ISSUE THREAD

**Issue by mboersma** [wal-e/wal-e#185]
The test suite for `wal-e` looks like it broke about 3 months ago: https://travis-ci.org/wal-e/wal-e/builds

I tried to figure it out and fix it, but honestly there are many errors and I got lost sorting out the Py26 issues locally. And there doesn't appear to be a "smoking gun" commit that broke things that I saw--maybe underlying requirements created the problem?

Anyway, as a new contributor to `wal-e` I feel a bit lost without knowing if my PRs fix things. If anyone has a pointer as to why the tests are broken, I would be glad to dig in and try again to fix them.

**Comment by fdr** [comment]
Well, I'm glad you saw fit to take a look.

One major issue is gevent's SSL support totally broke under Python 2.7.9, and some 2.7.8 backports.  

 Allegedly this is fixed, so perhaps refresh your gevent version if you haven't done that in a while: https://github.com/gevent/gevent/issues/477

Also, new versions of PEP8 are complaining about things they haven't in the past. I should probably suppress those, because I'm probably not going to churn the code that much in a point release.

I'll review the travis builds in a moment.

**Comment by fdr** [comment]
Okay, one major problem was Azure dropped Python 2.6 support. So, I did too. Sucks to do that in a point release, but given the time I can afford to expend I think this is my only choice.

**Comment by fdr** [comment]
Travis builds are green once more.

**Comment by mboersma** [comment]
Awesome thanks @fdr. I'll rebase my PR and hopefully it goes green as well.
