### ISSUE TITLE
wal-e not support Python 2.x anymore?

### ISSUE THREAD

**Issue by number5** [wal-e/wal-e#260]
https://github.com/wal-e/wal-e/blob/master/setup.py#L18

It would be great if wal-e can maintain Python 2.x support since a large part of the production systems will be still on Python 2.x platform. 

Like us, we have large part of our infrastructure required Python 2.x because of SaltStack,  and we probably will keep existing production environments on Python 2.x even if SaltStack able to move to Python 3.x

**Comment by fdr** [comment]
Are you finding this is because your installation via `pip install` is failing, or something, or did you happen to see the news?

You can continue to use `0.9.x` for, probably, a couple of years. If there's anything very serious I will backpatch a fix and make a release, but I haven't seen anything like that in a long time.

On the other hand, if something bitrots in a horrible way in the Python 2.7 versions of WAL-E's dependencies, I will not make extraordinary effort to save it.

**Comment by number5** [comment]
@fdr Thanks for clarification that 0.9.x will be maintained as a Python 2.7 version, that was a relief.
 
I was worried because of seeing this https://groups.google.com/forum/#!topic/wal-e/V-Vc_An9SeI and the  code in the master branch.

Thanks.
