### ISSUE TITLE
question about recovery.conf with wal-e

### ISSUE THREAD

**Issue by hanks** [wal-e/wal-e#306]
I saw some snippets like below:  

```
standby_mode     = 'on'
primary_conninfo = 'host=$HOST user=$USER password=$PASSWORD'
restore_command  = 'envdir /etc/wal-e.d/env wal-e wal-fetch "%f" "%p"'
trigger_file     = '/data/postgresql/9.1/main/trigger'
```

what does the `primary_conninfo` here mean, is it duplicated with the function of wal-e, to fetch the lastest XLOG file.

Thank you for your time.

**Comment by fdr** [comment]
Yeah, so basically, Postgres will source WAL from the archive (via WAL-E) or from another server (via `primary_conninfo`) and switches somewhat seamlessly between them (whenever one method has an error, the other method is tried, back and forth).

In principle, you only need one or the other. If you use WAL-E only (no `primary_conninfo`) then you will have higher replication latency (only full segments can be applied, and they are polled) and no hot-standby feedback (search for this feature by name if you are curious what it does). But, scalability is effectively unlimited.

By contrast, if one sets up `primary_conninfo` only, one will have streaming replication. The problem is then WAL can only be sourced from what is present on the primary, and recovery can get stuck if the primary no longer has the WAL to replay from the replication position the standby is at.

Some people use the former configuration, I surmise few use the latter arrangement because of limitations in replay. And most have both sources set.
